### ISSUE TITLE
Build failure in dev branch using colcon build

### ISSUE THREAD

**Issue by GuiMateus** [tesseract-robotics/tesseract_ros2#29]
It seems that some of the header includes are deprecated compared to the current version of tesseract.

![Screenshot from 2022-06-16 13-41-54](https://user-images.githubusercontent.com/43201054/174062755-948fe648-4eee-43ad-9105-4f6c28ee635c.png)

Changing `#include <tesseract_command_language/core/serialization.h>` to #include `<tesseract_common/serialization.h>` and `Serialization::` to `tesseract_common::Serialization:: `seems to fix this issue.

However, a new problem arises, since it seems the class `SimpleResourceLocator` does not seem to exist anymore in the current tesseract release.

![Screenshot from 2022-06-16 13-52-29](https://user-images.githubusercontent.com/43201054/174064288-66403b61-2d56-48da-abe6-b6d993326aa3.png)

Could you either fix these or give me some pointers on how to patch the second error? :)

Many thanks

**Comment by GuiMateus** [comment]
Managed to figure out the problem. Opened a merge request with a patch under https://github.com/tesseract-robotics/tesseract_ros2/pull/30 .

**Comment by rjoomen** [comment]
This can be closed, as the PR has been closed as well and all build failures have been solved.
