### ISSUE TITLE
Migrate tesseract_rviz to ROS2

### ISSUE THREAD

**Issue by schornakj** [tesseract-robotics/tesseract_ros2#3]

**Comment by mpowelson** [comment]
This is mostly done [here](https://github.com/mpowelson/tesseract_ros2/tree/feature/tesseract_rviz). I need to clean up some things, and then I'll submit a PR. It has the state widget and the trajectory widget just not the manipulation widget

**Comment by rjoomen** [comment]
Done in [this PR](https://github.com/marrts/tesseract_ros2/pull/4).
