### ISSUE TITLE
Ongoing development branch

### ISSUE THREAD

**Issue by jdlangs** [tesseract-robotics/tesseract_ros2#31]
The newest stuff is in `ros2-dev`, while `master` is significantly out of date now. I think they also don't even share a history since they started from two different versions of `tesseract_ros`. Should we delete the current `master` and rename the latest one to `master` or `main` or `rolling`?

**Comment by Levi-Armstrong** [comment]
I think deleting master and renaming the current ros2-dev to master sounds good to me.

**Comment by rjoomen** [comment]
Can we sort out which CI configurations should be supported (Jammy/Humble already works), see #35? Then @marrts repo with my [latest PR](https://github.com/marrts/tesseract_ros2/pull/4) can be merged into main and development can continue here.

**Comment by rjoomen** [comment]
Focal/Foxy CI now also builds correctly.

**Comment by rjoomen** [comment]
I think we're at a point where `ros2-dev` can be renamed to `master`. (Then confusions like #36 are solved as well, probably.)

**Comment by marrts** [comment]
Agreed, there is no reason to have this separate and `master` is useless at this point.

**Comment by marrts** [comment]
Done, now only the master branch exists.
