### ISSUE TITLE
Rviz crashing when I try to visualize the trajectory

### ISSUE THREAD

**Issue by srsidd** [tesseract-robotics/tesseract_ros2#62]
Hi, I'm having an issue when I try to visualize the trajectory generated. I can generate the trajectory, but rviz crashes when I hit the play button or use the slider to visualize the trajectory - 
![Untitled drawing (1)](https://github.com/tesseract-robotics/tesseract_ros2/assets/10639113/aa0faaa7-6dd4-4aeb-9be2-141f33a1160a)

Even when I click on each state the robot model in the main window does not update - 
![Screenshot from 2023-08-27 08-57-18](https://github.com/tesseract-robotics/tesseract_ros2/assets/10639113/09fe1b89-b34f-4582-a857-49e0f6f84d2c)

This is the error message from rviz - 

```bash
[ERROR] [rviz2-3]: process has died [pid 49694, exit code -11, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d /home/srsidd//ws/install/snp_bringup_ros2/share/snp_bringup_ros2/config/app.rviz --ros-args --params-file /tmp/launch_params_vl8p0ziv --params-file /tmp/launch_params_ab0_c_da --params-file /tmp/launch_params_0bu74zre --params-file /tmp/launch_params_p3ipk81l --params-file /tmp/launch_params_es_iy2eb --params-file /tmp/launch_params_qo2ep6mk --params-file /tmp/launch_params_6pbtysve --params-file /tmp/launch_params_ckx63_9h --params-file /tmp/launch_params_x6tz62ew --params-file /tmp/launch_params_65pq0kf1'].
```

I am using tesseract `v0.18.1`, tesseract_planning `v0.18.3`.  and tesseract_ros2 with commit has `f7147aa20d8055953d49c6dcb7f144ef6de65d17` on Ubuntu 22.04 with Humble.

I am using tesseract `v0.18.1` and tesseract_planning `v0.18.3`.  on Ubuntu 22.04 with Humble.

Any thoughts on what could be wrong?

**Comment by Levi-Armstrong** [comment]
@marrts or @rjoomen Have you been using the rviz plugins for ros2?

**Comment by peik-etzell** [comment]
I have had rviz crash on me if I click on the trajectory right away, as if I have to wait for rviz to load the trajectory in the background first. The symptoms are similar at least.

**Comment by marrts** [comment]
I have had similar issues in the past, but haven't gotten around to investigating it. At one point I believe it was getting triggered whenever I would save an new rviz config file which would get used at launch. Almost like there was a field in there that was causing an issue. Like I said, I haven't had the chance to dig into it, but it seemed like maybe it was somehow related to the snapshot field in the workbench, which I think is somewhat new.

**Comment by srsidd** [comment]
Based on the comment from @marrts, I did some more testing and found it has something to do with the `TesseractWorkbench` being part of the rviz config. When I start rviz without the `TesseractWorkbench` but add it manually after it comes up I can plan and visualize the trajectory without rviz crashing.
However, when the `TesseractWorkbench` plugin is part of the rviz config that comes up, the application crashes when I try the `TrajectorySlider`.

I also found if the default rviz config has a `TesseractWokbench` already loaded, but before planning I remove it and add a new one instead and update the topics accordingly, I can visualize the trajectory without the slider crashing rviz2.

Any pointers on where to look for this bug?

**Comment by Levi-Armstrong** [comment]
It is most likely with the function for loading the config are not correctly setting up the widget.

**Comment by rjoomen** [comment]
It has to do with the new snapshot functionality. I submitted PRs #70 and tesseract-robotics/tesseract_ros#226

**Comment by rjoomen** [comment]
@srsidd has this been solved?

**Comment by srsidd** [comment]
Yes, thanks for the PR. I am going to close the issue.
