### ISSUE TITLE
rviz_common package not found

### ISSUE THREAD

**Issue by LuciferMorningStar0786** [tesseract-robotics/tesseract_ros2#66]
Hi everyone,

I was trying out tesseract_ros2 in ros2foxy,
there is on issue in colcon build but,
when i run this command  

ros2 launch tesseract_ros_examples basic_cartesian_example.launch.xml 

rviz is not opening 

#issue

from pkg_resources import load_entry_point
[INFO] [launch]: All log files can be found below /home/kaayatech/.ros/log/2023-09-11-12-33-56-167002-kaayatech-Predator-61640
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [static_transform_publisher-1]: process started with pid [61660]
[INFO] [tesseract_ros_examples_basic_cartesian_example_node-2]: process started with pid [61662]
[INFO] [rviz2-3]: process started with pid [61664]
[static_transform_publisher-1] /opt/ros/foxy/lib/tf2_ros/static_transform_publisher: symbol lookup error: /opt/ros/foxy/lib/libstatic_transform_broadcaster_node.so: undefined symbol: _ZN12class_loader4impl22AbstractMetaObjectBaseC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_
[ERROR] [static_transform_publisher-1]: process has died [pid 61660, exit code 127, cmd '/opt/ros/foxy/lib/tf2_ros/static_transform_publisher 0 0 0 0 0 0 world base_link --ros-args -r __node:=virtual_joint_broadcaster_0'].
[rviz2-3] [rospack] Error: package 'rviz_common' not found
[rviz2-3] [librospack]: error while executing command
[tesseract_ros_examples_basic_cartesian_example_node-2] [INFO] [1694415836.997449252] [basic_cartesian_example_node.ROSEnvironmentMonitor_internal.tesseract_ros_examples_monitor]: Updating internal planning scene state at most every 0.100000 seconds
[tesseract_ros_examples_basic_cartesian_example_node-2] [INFO] [1694415837.000173041] [basic_cartesian_example_node.ROSEnvironmentMonitor_internal.tesseract_ros_examples_monitor]: Publishing maintained environment on '/tesseract_ros_examples/tesseract_published_environment'
[tesseract_ros_examples_basic_cartesian_example_node-2] [INFO] [1694415837.000223511] [basic_cartesian_example_node.ROSEnvironmentMonitor_internal.tesseract_ros_examples_monitor]: Started environment state publishing thread ...
[rviz2-3] [INFO] [1694415837.196044654] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1694415837.196164792] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)

**[rviz2-3] [rospack] Error: package 'rviz_common' not found
[rviz2-3] [librospack]: error while executing command
[rviz2-3] [rospack] Error: package 'rviz_common' not found
[rviz2-3] [librospack]: error while executing commandrviz2-3] [rospack] Error: package 'rviz_common' not found
[rviz2-3] [librospack]: error while executing command
[rviz2-3] [rospack] Error: package 'rviz_common' not found
[rviz2-3] [librospack]: error while executing command**

[rviz2-3] [INFO] [1694415837.264861362] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] corrupted double-linked list
[ERROR] [rviz2-3]: process has died [pid 61664, exit code -6, cmd '/opt/ros/foxy/lib/rviz2/rviz2 -d /home/kaayatech/snpd_workspace/install/tesseract_ros_examples/share/tesseract_ros_examples/config/examples.rviz --ros-args --params-file /tmp/launch_params_hw0oclah --params-file /tmp/launch_params_fn06ls0u'].
[tesseract_ros_examples_basic_cartesian_example_node-2] [INFO] [1694415838.500624646] [basic_cartesian_example_node.ROSEnvironmentMonitor_internal.tesseract_ros_examples_monitor]: Published the Tesseract Environment State for: 'kuka_lbr_iiwa_14_r820'

When I run 
ros2 pkg list | grep rviz_common to check rviz_comman  pkg is there 

#terminal 
/opt/ros/foxy/bin/ros2:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
rviz_common

Package is already there

Please help me out in this resloving the issue

**Comment by rjoomen** [comment]
@LuciferMorningStar0786 can we close this issue?
