### ISSUE TITLE
Issue in Colocn build in foxy

### ISSUE THREAD

**Issue by LuciferMorningStar0786** [tesseract-robotics/tesseract_ros2#67]
Hi greetings all,

I am using tesseract_ros2 in foxy 
when i start build it 

#issue
          
--- stderr: tesseract_time_parameterization                                                                                                                                               
CMake Warning at /home/kaayatech/foxy_vivek_ws/install/ros_industrial_cmake_boilerplate/lib/cmake/ros_industrial_cmake_boilerplate/cmake/code_coverage.cmake:162 (message):
  Code coverage results with an optimized (non-Debug) build may be misleading
Call Stack (most recent call first):
  CMakeLists.txt:30 (initialize_code_coverage)

Building ISP
Building TOTG
Building Ruckig
CMake Error at ruckig/CMakeLists.txt:1 (find_package):
  By not providing "Findruckig.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ruckig", but
  CMake did not find one.

  **Could not find a package configuration file provided by "ruckig" with any
  of the following names:

    ruckigConfig.cmake
    ruckig-config.cmake**

  Add the installation prefix of "ruckig" to CMAKE_PREFIX_PATH or set
  "ruckig_DIR" to a directory containing one of the above files.  If "ruckig"
  provides a separate development package or SDK, be sure it has been
  installed.

make: *** [Makefile:294: cmake_check_build_system] Error 1
---
Failed   <<< tesseract_time_parameterization [0.28s, exited with code 2]

i have installed ruckig pkg using this command 

pip install ruckig

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ruckig in /home/kaayatech/.local/lib/python3.8/site-packages (0.9.2)

its already installed 

still getting that above error please help me out to install the package

**Comment by Levi-Armstrong** [comment]
Are you using version 0.19.X of tesseract and tesseract_planning?

**Comment by marip8** [comment]
Installing `ruckig` via `pip` won't work because it doesn't install CMake files, headers, or a shared library for building/linking to the `tesseract` interface

**Comment by LuciferMorningStar0786** [comment]
> Are you using version 0.19.X of tesseract and tesseract_planning?

yes

**Comment by LuciferMorningStar0786** [comment]
Again Hi,

So as u told me, using this command to colcon build

colcon build --cmake-args -DTESSERACT_BUILD_FCL=OFF -DBUILD_RENDERING=OFF -DTESSERACT_BUILD_RUCKIG=OFF

now getting issues in

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at planning/CMakeLists.txt:87 (add_library):
  Target "tesseract_task_composer_planning_factories" links to target
  "tesseract::tesseract_time_parameterization_ruckig" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


**CMake Error at planning/CMakeLists.txt:30 (add_library):
  Target "tesseract_task_composer_planning_nodes" links to target
  "tesseract::tesseract_time_parameterization_ruckig" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?**


CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_RENDERING
    TESSERACT_BUILD_FCL
    TESSERACT_BUILD_RUCKIG


CMake Generate step failed.  Build files cannot be regenerated correctly.
---
Failed   <<< tesseract_task_composer [12.1s, exited with code 1]


so how should reslove the issues now

**Comment by marip8** [comment]
To use that optional build feature, you need to be on version 0.19.x for `tesseract` `tesseract_planning`, and `tesseract_qt`, and presumably the master branch for this repo

**Comment by Levi-Armstrong** [comment]
@marip8 is correct. The propagation of these build flags should be addressed in the latest version 0.19.X. Let us know if you still have issues after upgrading to version 0.19.X.

**Comment by LuciferMorningStar0786** [comment]
Hi @marip8 and @Levi-Armstrong. I am using latest version 0.19.x. Colcon build was successful thankyou for that but there is an issue while launch tesseract_ros_example of 

 ros2 launch tesseract_ros_examples basic_cartesian_example.launch.xml 

#issue   
      
**[rviz2-3] [ERROR] [1695040317.892526296] [rviz2]: PluginlibFactory: The plugin for class 'rviz_common/Time' failed to load. Error: According to the loaded plugin descriptions the class rviz_common/Time with base class type rviz_common::Panel does not exist. Declared types are** 
[tesseract_ros_examples_basic_cartesian_example_node-2] [INFO] [1695040317.913978075] [basic_cartesian_example_node.ROSEnvironmentMonitor_internal.tesseract_ros_examples_monitor]: Published the Tesseract Environment State for: 'kuka_lbr_iiwa_14_r820'
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
[rviz2-3] (Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] QObject::connect: Cannot queue arguments of type 'Qt::Orientation'
[rviz2-3] (Make sure 'Qt::Orientation' is registered using qRegisterMetaType().)
[rviz2-3] [INFO] [1695040317.948553226] [rviz.TesseractWorkbench_EnvMonitor_Node.ROSEnvironmentMonitor_internal.workbench_display_0_monitor]: Updating internal planning scene state at most every 0.100000 seconds
[tesseract_ros_examples_basic_cartesian_example_node-2] You can set logging level with TRAJOPT_LOG_THRESH. Valid values: FATAL ERROR WARN INFO DEBUG TRACE. Defaulting to ERROR
[tesseract_ros_examples_basic_cartesian_example_node-2] Program: Composite Instruction, Description: Tesseract Composite Instruction
[tesseract_ros_examples_basic_cartesian_example_node-2] Program: {
[tesseract_ros_examples_basic_cartesian_example_node-2] Program:   Move Instruction, Move Type: 1, State WP: Pos=   -0.4  0.2762       0 -1.3348       0  1.4959       0
[tesseract_ros_examples_basic_cartesian_example_node-2] , Description: Start Instruction
[tesseract_ros_examples_basic_cartesian_example_node-2] Program:   Move Instruction, Move Type: 1, Cart WP: xyz=0.5, -0.2, 0.62
[tesseract_ros_examples_basic_cartesian_example_node-2] , Description: from_start_plan
[tesseract_ros_examples_basic_cartesian_example_node-2] Program:   Move Instruction, Move Type: 0, Cart WP: xyz=0.5, 0.3, 0.62
[tesseract_ros_examples_basic_cartesian_example_node-2] , Description: Tesseract Move Instruction
[tesseract_ros_examples_basic_cartesian_example_node-2] Program:   Move Instruction, Move Type: 1, State WP: Pos=   -0.4  0.2762       0 -1.3348       0  1.4959       0
[tesseract_ros_examples_basic_cartesian_example_node-2] , Description: to_end_plan
[tesseract_ros_examples_basic_cartesian_example_node-2] Program: }

#issue in rviz_display

![rviz_display](https://github.com/tesseract-robotics/tesseract_ros2/assets/135658287/d0eebf7e-8954-4084-8231-794a0199c8ee)


Help me out resolve this think...it will be helpful

**Comment by LuciferMorningStar0786** [comment]
Yess demo itself not working... Its showing me the trajectories tab but not able to run that trajectory

**Comment by LuciferMorningStar0786** [comment]
And my aim is to ingrate UR10e with this motion planning with Hardware real time...

1. I tried with UR10e thing with ros noetic where, i am not getting rviz_common issue its working well...I am able to run all tessarct_ros_examples with out any issues but for ros_noetic there is no hardware support for the Universal robot...
2. So me trying out in tessarct_ros2 pkg for motion planning so that i am easily able to control ur10e hardware in ros2foxy

Please help me out me to in this or is there any another way to control UR10e hardware in ros2foxy @Levi-Armstrong and @marip8

**Comment by LuciferMorningStar0786** [comment]
@marip8 for this branch there is no support hardware support of universal robot.... I have tried it already

**Comment by rjoomen** [comment]
@LuciferMorningStar0786 can we close this issue?
